### PR TITLE
Fix/phpcs

### LINKED ISSUE #198: PHPCS does not scan mu-plugins folder
https://github.com/10up/wp-scaffold/blob/trunk/phpcs.xml#L5

This pattern should be ./plugins/*

### LINKED ISSUE #219: PHPCS Broken
### Describe the bug

Since #206 was merged, PHPCS has been broken on commit. This is because it moved the lintstaged config to the theme & plugin and they don't contain the PHPCS config, nor the executable. 

We should either:

1. Find a way to allow PHP linting to run from the root, whilst allowing eslint to use the configs from each directory
2. Revert the lintstaged change for now
3. Install and configure PHPCS and it's rules within each directory (but this adds a lot of config overhead)

### Steps to Reproduce

* Clone the repo.
* Make a change within a PHP file.
* Commit.
* See PHPCS error in the pre-commit hook.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by darylldoyle**
### Description of the Change
This PR does a couple of things:

* Fixes an issue where PHPCS was not running when changes were made in the theme or plugin
* Upgrades the 10up PHPCS to the latest version
* Fixes current PHPCS issues
* Adds a PHPCS check to Github Actions within the scaffold

Closes #219 
Closes #216 
Closes #198 

### How to test the Change
* Run PHPCS

### Credits

Props @darylldoyle @Jamesking56

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: mu-plugins/10up-plugin/plugin.php [hunk 1]
```diff
@@ -1,4 +1,20 @@
...
+ * Requires at least: 4.9
+ * Requires PHP:      7.2
+ * Author:            10up
+ * Author URI:        https://10up.com
+ * License:           GPL v2 or later
+ * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
+ * Text Domain:       tenup-plugin
+ * Domain Path:       /languages
+ * Update URI:        https://github.com/10up/wp-scaffold
+ *
```
Comment (fabiankaegy) [inline mu-plugins/10up-plugin/plugin.php:15]: Isn't all this metadata that never actually shows anywhere since mu-plugins are using the plugin loader approach?

File: phpcs.xml [hunk 2]
```diff
@@ -1,9 +1,24 @@
...
 	<description>10up PHPCS extended.</description>
+
+	<!-- Scan these directories -->
+	<file>./themes/*</file>
+	<file>./mu-plugins/*</file>
+
+	<!-- Don't scan these directories -->
 	<exclude-pattern>dist/</exclude-pattern>
-	<exclude-pattern>plugins/*</exclude-pattern>
+	<exclude-pattern>./plugins/*</exclude-pattern>
```
Comment (fabiankaegy) [inline phpcs.xml]: I feel like this will cause issues pretty soon. To me there are valid reasons why I may need to add custom plugins to the plugins directory and 3rd party plugins to the mu-plugins folder. 

Maybe it makes more sense to not use any wildcards but explicitly specify the folders we want?

**Review by fabiankaegy — APPROVED** [review]
Left two suggestions / questions. But this is great :)

**Review by ivanlopez — APPROVED** [review]

File: mu-plugins/10up-plugin/plugin.php (hunk 1 above)
Comment (darylldoyle) [reply mu-plugins/10up-plugin/plugin.php:15]: Correct, though it's not uncommon for someone to copy-paste the mu-plugin as a scaffold for a standard plugin, in which case it's helpful to have this in place.

File: phpcs.xml (hunk 2 above)
Comment (darylldoyle) [reply phpcs.xml]: I'm happy with that. Updated to exclude `node_modules` and `vendor` but include `plugins` by default
