### PR TITLE
Change deprecated block_categories filter to block_categories_all

### LINKED ISSUE #55: Filter block_categories is deprecated as of WordPress 5.8
The filter `block_categories` is deprecated as of WP 5.8.0 in favor of `block_categories_all`

**Steps to Reproduce**

1. Install Block Library plugin and activate
2. Activate all blocks with filter in README
3. set WP_DEBUG to true
4. Create a new post
5. Expected behavior
6. Expected to only see the editor.

**Describe the bug** 

Saw the editor along with deprecation warning messages in the admin nav menu

**Expected behavior**

Should not see any warnings when `WP_DEBUG` is set to `true`

**Environment information**
 - WordPress version: 5.8

### PR DESCRIPTION
**Pull request by claytoncollie**
### Description of the Change

Fixes warning saying that `block_categories` has been deprecated in favor of `block_categories_all`.

https://developer.wordpress.org/reference/hooks/block_categories/

https://developer.wordpress.org/reference/hooks/block_categories_all/

### Verification Process

1. Set `WP_DEBUG` to `true` in wp-config.php
2. Go to the block editor in wp-admin
2. Select the main block inserter on the top left of the screen
3. Scroll to the bottom of the block list looking for the Custom Blocks category

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.

### Applicable Issues

#55 

### Changelog Entry

Changed filter `block_categories` to `block_categories_all`

### CODE REVIEW

File: themes/10up-theme/includes/blocks.php [hunk 1]
```diff
@@ -93,12 +93,12 @@ function blocks_editor_styles() {
...
  * @param array  $categories Registered categories.
- * @param object $post       The post object.
+ * @param object $block_editor_context The current block editor context.
  *
  * @return array Filtered categories.
  */
-function blocks_categories( $categories, $post ) {
-	if ( ! in_array( $post->post_type, array( 'post', 'page' ), true ) ) {
+function blocks_categories( $categories, $block_editor_context ) {
+	if ( ! in_array( $block_editor_context->post->post_type, array( 'post', 'page' ), true ) ) {
```
Comment (ryanwelcher) [inline themes/10up-theme/includes/blocks.php]: Does this account for custom post types?

Comment (claytoncollie-dmv) [reply themes/10up-theme/includes/blocks.php:101]: @ryanwelcher It doesn't look like it. Looking at the code on `trunk` and it has [this same guard clause](https://github.com/10up/wp-scaffold/blob/7f573eaaf2294b7c88a5034b7ba76766fcc57ca0/themes/10up-theme/includes/blocks.php#L101) for Posts and Pages. I'm guessing the original author assumed most blocks are made for built-in post types and doesn't want to clutter up custom post types. FWIW, I'm fine removing it.

Comment (claytoncollie) [reply themes/10up-theme/includes/blocks.php]: @ryanwelcher It doesn't look like it. Looking at the code on trunk and it has this same guard clause for Posts and Pages. I'm guessing the original author assumed most blocks are made for built-in post types and doesn't want to clutter up custom post types. FWIW, I'm fine removing it.

Comment (fabiankaegy) [reply themes/10up-theme/includes/blocks.php]: @claytoncollie I agree that we should remove this check and have it apply to all editor contexts. Can you make that change?

Comment (claytoncollie-dmv) [reply themes/10up-theme/includes/blocks.php]: All done.

Comment (claytoncollie) [reply themes/10up-theme/includes/blocks.php]: All done @fabiankaegy

**Review by fabiankaegy — APPROVED** [review]
Looks great  👍 Thanks for the Update :)

**Comment by fabiankaegy** [comment]
@joesnellpdx This is ready for your review and to be merged
